<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class InformeDetalladoDetalle extends Model
{
    protected $table="informe_detallado_detalle";
    
    public   $timestamps=false;
     
    protected $fillable = [
        'type',
        'created_at', 
        'updated_at', 
        'salon', 
        'tamano_aproximado_salon', 
        'muebles_salon', 
        'venta_salon', 
        'orientacion_salon', 
        'tipo_ventana_salon', 
        'pintura_salon', 
        'tipo_suelo_salon', 
        'aire_condicionado_salon', 
        'nota_salon', 
        'cocina', 
        'tanano_aproximado_cocina', 
        'estado_cocina', 
        'tipo_cocina', 
        'ventana_cocina', 
        'tipo_ventana_cocina', 
        'equipaje_cocina', 
        'tipo_fuego_cocina', 
        'tipo_suelo_cocina', 
        'nota_cocina', 
        'dormitorio', 
        'tamano_aproximado_dormitorio', 
        'en_suite', 
        'tamano_dormitorio', 
        'tipo_cama_dormitorio', 
        'armarios_dormitorio', 
        'ventana_dormitorio', 
        'orientacion_dormitorio', 
        'tipo_ventana_dormitorio', 
        'aire_condicionado_dormitorio', 
        'pintura_dormitorio', 
        'tipo_suelo_dormitorio', 
        'nota_dormitorio', 
        'salon_dormitorio', 
        'tamano_aprox_salon', 
        'muebles_dormitorio_salon', 
        'ventana_dormitorio_salon', 
        'orientacion_dormitorio_salon', 
        'tipo_ventana_dormitorio_salon', 
        'pintura_dormitorio_salon', 
        'tipo_suelo_dormitorio_salon', 
        'aire_condicionado_dormitorio_salon', 
        'tipo_cama_dormitorio_salon', 
        'armarios_dormitorio_saldon', 
        'nota_dormitorio_salon', 
        'banos', 
        'tamano_aprox_banos', 
        'bano_dentro_dormitorio', 
        'estado_reforma_banos', 
        'babera_banos', 
        'venta_banos', 
        'tipo_ventana', 
        'tipo_suelo_banos', 
        'aseo_banos', 
        'nota_banos', 
        'pasillo', 
        'tamano_aprox_pasillo', 
        'armario_pasillo', 
        'almacenamiento_pasillo', 
        'nota_pasillo', 
        'habatacion_servicio', 
        'tanano_aprox_habitacion_servicio', 
        'nota_habitacion_servicio', 
        'banos_servicios', 
        'tamano_aprox_bano_servicios', 
        'estado', 
        'salon_estrenar_tipo_ventana', 
        'salon_cambiado_hace_tipo_ventana', 
        'salon_puesta_hace_tipo_ventana', 
        'salon_pintuta_cambiada_hace', 
        'salon_tipo_suelo_estrenar', 
        'salon_tipo_suelo_cambiado', 
        'salon_tipo_suelo_puesto', 
        'cocina_tipo_ventana_estrenar', 
        'cocina_tipo_ventana_cambiado', 
        'cocina_tipo_ventana_puesta', 
        'cocina_tipo_suelo_estrenar', 
        'cocina_tipo_suelo_cambiado', 
        'cocina_tipo_suelo_puesto', 
        'dormitorio_tipo_ventana_estrenar', 
        'dormitorio_tipo_ventana_cambiado', 
        'dormitorio_tipo_ventana_puesto', 
        'dormitorio_pintura_recien', 
        'dormitorio_pintura_recien_pintada', 
        'dormitorio_tipo_suelo_estrenar', 
        'dormitorio_tipo_suelo_cambiado', 
        'dormitorio_tipo_suelo_puesto', 
        'salon_tipo_ventana_estrenar', 
        'salon_tipo_ventana_cambiado', 
        'salon_tipo_ventana_puesto', 
        'salon_pintura_recien', 
        'salon_pintura_recien_pintada', 
        'bano_tipo_ventana_estrenar', 
        'bano_tipo_ventana_cambiado', 
        'bano_tipo_ventana_puesto', 
        'bano_tipo_suelo_estrenar', 
        'bano_tipo_suelo_cambiado', 
        'bano_tipo_suelo_puesto', 
        'salon_para', 
        'salon_pared', 
        'salon_dormitorio_balcon_m', 
        'salon_dormitorio_tereza_m', 
        'sepuede_sacar_algo_mueble_salon', 
        'salon_dclimati', 
        'cocina_balcon_m', 
        'cocina_terreza_m', 
        'cocina_equipaje_extractor', 
        'cocina_equipaje_microondas', 
        'cocina_equipaje_horno', 
        'cocina_equipaje_nevera', 
        'cocina_equipaje_lavadora', 
        'cocina_equipaje_secadora', 
        'cocina_fuego_vitroceramica', 
		'cocina_fuego_induccion', 
        'cocina_fuego_gas_nuevo', 
        'cocina_fuego_placa_electronica', 
        'cocina_dclimati', 
        'sepuede_sacar_algo_mueble_cocina', 
        'dormitorio_balcon_m', 
        'dormitorio_terreza_m', 
        'dormirotio_pared', 
        'sepuede_sacar_algo_mueble_dormirorio', 
        'dormitorio_dclimati', 
        'salon_dormitorio_pared', 
        'salon_dormitorio_balcon_m', 
        'salon_dormitorio_tereza_m', 
        'salon_dormitorio_cuantas_personas', 
        'salon_dorimitorio_puertas', 
        'salon_dormitorio_dclimati', 
        'salon_dormitorio_tipo_suelo_estrenar',
        'salon_dormitorio_tipo_suelo_cambiado',
        'salon_dormitorio_tipo_suelo_puesto',
        'sepuede_sacar_algo_mueble_salon_dormitorio', 
        'banos_banera', 
        'banos_ducha', 
        'banos_bide', 
        'banos_jacuzzi', 
        'bano_dclimati', 
        'sepuede_sacar_algo_mueble_bano', 
        'banos_suite', 
        'pasillo_puertas', 
        'sepuede_sacar_algo_mueble_pasillo', 
        'cocina_estado_estrenar', 
        'cocina_estado_reformada', 
        'cocina_equipaje_lavavajillas', 
        'dormitorio_armarios_dormitorio_puertas', 
        'dormitorio_pared', 
        'banos_estado_estrenar', 
        'banos_estado_reformada', 
        'aseo_aprox_pasillo', 
        'tanano_aprox_distribuidor', 
        'armarios_distribuidor', 
        'distribuidor_armarios_puertas', 
        'sepuede_sacar_algo_mueble_distribuidor', 
        'fk_id_informe_detallado_cabecera', 
        'user_id',
        'puerta',
        'tamano_prox_recibidor',
        'aparador',
        'armario',
        'almacenamiento',
        'sepuede_sacar_algo_mueble_recibidor',
        'armario_num_puertas',
		'sepuede_sacar_algo_mueble_bathServices',
		'sepuede_sacar_algo_mueble_restrooms',
		'sepuede_sacar_algo_mueble_serviceRooms',
		'cocina_equipaje_menaje',
		'cocina_equipaje_lavadero',
		'salon_muebles_sofa',
		'salon_muebles_sofa_cama',
		'salon_muebles_tv',
		'salon_muebles_mesa_comedor',
		'dormitorio_muebles_sofa',
'dormitorio_muebles_sofa_cama',
'dormitorio_muebles_tv',
'dormitorio_muebles_mesa_comedor',
'dormitorio_muebles_escritorio',
'dormitorio_muebles_comoda',
'salon_dormitorio_muebles_sofa',
'salon_dormitorio_muebles_sofa_cama',
'salon_dormitorio_muebles_tv',
'salon_dormitorio_muebles_mesa_comedor',
'salon_dormitorio_muebles_escritorio',
'salon_dormitorio_muebles_comoda',
'descripcion',
'tamano',
'tipo',
'numero',
'situacion',
'tipo_transporte',
'parada',
'lineas',
'medida',
'unidad_medida',
'medio',
'lineas_1',
'medida_1',
'unidad_medida_1',
'medio_1',
'lineas_2',
'medida_2',
'unidad_medida_2',
'medio_2',
'lineas_3',
'medida_3',
'unidad_medida_3',
'medio_3',
'lineas_4',
'medida_4',
'unidad_medida_4',
'medio_4',
'lineas_5',
'medida_5',
'unidad_medida_5',
'medio_5',
'lineas_6',
'medida_6',
'unidad_medida_6',
'medio_6',
'lineas_7',
'medida_7',
'unidad_medida_7',
'medio_7',
'lineas_8',
'medida_8',
'unidad_medida_8',
'medio_8',
'lineas_9',
'medida_9',
'unidad_medida_9',
'medio_9',
'precio',
'barrio',
'gasto'
    ];
	

    protected $appends = ['title'];

    public function multimedia() {
        return $this->hasMany('App\Multimedia', 'fk_id_informe_detallado_detalle');
    }

	/* public function transporte() {
        return $this->hasMany('App\Transporte', 'fk_id_informe_detallado_detalle');
    }*/

    public function cabecera()
    {
        return $this->hasOne('App\InformeDetalladoCabecera', 'id', 'fk_id_informe_detallado_cabecera');
    }

    public function getTitleAttribute()
    {
        $labels = [
            'Salón',
            'Cocina',
            'Dormitorio',
            'Salón - Dormitorio',
            'Baño',
            'Aseo',
            'Pasillo',
            'Distribuidor',
            'Habitación de servicio',
            'Baño de servicio',
            'Recibidor',
            'Puerta',
			'Garaje',
			'Trastero',
			'Fachada',
			'Portal',
			'Ascensor',
			'Piscina',
			'Jardin',
			'Gimnasio',
			'Sauna',
			'Zona Deportiva',
			'Zona Infantil',
			'Transporte',
			'Lugares de interés'
        ];
        
        return $labels[$this->type];
    }
}
