<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
        <style>
        h5{
        text-align: center;
        text-transform: uppercase;
        }		
        h1{
        text-align: center;
        text-transform: uppercase;
        }
		.texto-justificado{
		text-align: justify;
		}
		.texto-justificado-derecha{
		text-align: right;
		}		
        .contenido{
        font-size: 16px;
        }
        #primero{
        background-color: #ccc;
        }
        #segundo{
        color:#44a359;
        }
        #tercero{
        text-decoration:line-through;
        }
    </style>
    </head>
    <body>
        <h1>Términos y condiciones</h1>
        <div class="contenido">			
			<p class="texto-justificado-derecha">Última fecha de actualización:<?php   if (isset($fecha_letra))
																{echo $fecha_letra;}
															else
																{echo '..........................';}
															?>.</p>
            <pre style='display:inline'>&#09;</pre>
			<h5>1.-IDENTIFICACIÓN Y COMUNICACIONES</h5>
				<p>1.1 - De una parte, la mercantil <b>IAMOVING ONLINE, S.L.</b>, con CIF B-88297825, y domicilio en la Calle Serrano, número 93, 3º E (28006-Madrid), correo electrónico: <a href="&#109;&#097;&#105;&#108;&#116;&#111;:&#105;&#110;&#102;&#111;&#064;&#105;&#097;&#109;&#111;&#118;&#105;&#110;&#103;&#046;&#099;&#111;&#109;">info@iamoving.com</a>, teléfono +34 914 870 849, móvil +34 649 623 700; representada en este acto por D. Roberto Santucci, mayor de edad, con NIF X8880708-V. En adelante “IAMOVING”</p>
            <p>1.2 - De otra parte, D./Dª. <?php if (isset($name))
															{echo $name;}
															else
															{echo '..........................';}
															?>, mayor de edad, con NIF <?php if (isset($dni))
															{echo $dni;}
															else
															{echo '..........................';}
															?>, y domicilio a efectos de notificaciones en <?php if (isset($address))
															{echo $address;}
															else
															{echo '..........................';}
															?>
															teléfono <?php if (isset($phone))
															{echo $phone;}
															else
															{echo '...........';}
															?> y correo electrónico:<?php if (isset($email))
															{echo $email;}
															else
															{echo '..........................';}
															?>, en adelante “EL COLABORADOR“.</p>
			<p>1.3 - Todas las notificaciones y comunicaciones entre los colaboradores y IAMOVING se considerarán eficaces a todos los efectos, cuando se realicen a través de cualquier de los medios detallados anteriormente.</p>
			<p>1.4 - EL colaborador se obliga a hacer un uso correcto de LA PLATAFORMA, de conformidad con las leyes, la buena fe, el orden público, los usos del tráfico y el presente Aviso Legal. El colaborador responderá frente a IAMOVING y BED4EXCHANGE o frente a terceros, de cualesquiera daños y perjuicios que pudieran causarse como consecuencia del incumplimiento de dicha obligación.</p>
			<p>1.5 - Constituye el objeto del presente término de prestación de servicios por el agente colaborador para IAMOVING ONLINE, S.L. y BED4EXCHANGE, según se regula en la legislación vigente. La relación que se constituye entre el colaborador y IAMOVING ONLINE, S.L. será exclusivamente de carácter mercantil.</p>
            <h5>2.-SERVICIOS PRESTADOS POR EL COLABORADOR, DÍAS Y HORARIOS: dicho colaborador podrá desarrollar de una hasta todas las funciones que están mencionadas inmediatamente debajo.</h5>
			<!--<p>2.1-PAQUETE DE SERVICIOS QUE OFRECE EL COLABORADOR A IAMOVING</p>
			<p>Los servicios prestados por el colaborador deben ser los siguientes:</p>-->
			<p>&nbsp; &nbsp; &nbsp; &nbsp; a. <b>COLABORADOR COMERCIAL PARA IAMOVING INMOBILIARIA</b>. Comercial en la captación de nuevos propietarios para IAMOVING y su posterior publicación en la misma, desde cuando el inmueble interese a la plataforma.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; b. <b>COLABORADOR AUDIOVISUAL IAMOVING</b>. Realización de reportaje audiovisual de inmuebles a la plataforma IAMOVING (consiste en dirigirse al inmueble, tomar fotos y vídeos, además de editar y realizar los informes pertinentes y los anuncios en <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a> y en <a href="https://www.idealista.com" style="color:#EADD03;">www.idealista.com</a>, bajo las instrucciones de IAMOVING).</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; c. <b>COLABORADOR FOTOGRÁFICO IAMOVING</b>. Consiste en dirigirse al inmueble, tomar fotos y un vídeo rápido sencillo vertical, y realizar los informes pertinentes y los anuncios en <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a> y en <a href="https://www.idealista.com" style="color:#EADD03;">www.idealista.com</a>, bajo las instrucciones de IAMOVING.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; d. <b>CREADOR DE ANUNCIOS IAMOVING</b>. Consiste en bajar las fotos de enlaces establecidos por Iamoving y realizar los informes pertinentes y los anuncios en  <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a> y en <a href="https://www.idealista.com" style="color:#EADD03;">www.idealista.com</a>, bajo las instrucciones de IAMOVING.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; e. <b>COLABORADOR DE VISITAS</b>. Se encarga de mostrar inmuebles a posibles compradores o arrendatarios representando a la plataforma IAMOVING.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; f. <b>COLABORADOR COMERCIAL PARA LA PLATAFORMA <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a></b>. El colaborador recomendará a un máximo de 5 personas de ciertas ciudades, bajo las peticiones de BED4EXCHANGE para que publiquen su habitación en la plataforma <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a>.  El COLABORADOR, recibirá un número de referencia que deberá proporcionar a las personas que vayan a publicar su habitación en la plataforma <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a>, para que éstas, utilicen esta referencia al registrase y publicar su habitación en la PLATAFORMA. En el caso que BED4EXCHANGE, <u>necesitará nuevamente los servicios del colaborador, es decir de 5 recomendaciones más el colaborador será notificado por escrito (por WhatsApp o email)</u>.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; g. <b>COLABORADOR AUDIOVISUAL <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a></b>. Consiste en bajar imágenes del Google free, fotos y video, de ciertos anuncios publicados en la plataforma y crear un video rápido (máximo1 minuto de duración), bajo las instrucciones de la plataforma.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; h. <b>COLABORADOR INFUENCER INMOBILIARIO IAMOVING</b>. Este colaborador podrá publicar determinados inmuebles que estén ya anunciados en la plataforma IAMOVING en sus redes sociales: FACEBOOK, INSTAGRAM Y TIK TOK, siempre bajo la previa autorización de IAMOVING. El colaborador influencer inmobiliario percibirá una comisión por cada inmueble que IAMOVING alquile o venda, y en los que el haya participado en la comercialización de este inmueble indicando a la plataforma el comprador o el inquilino.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; i. <b>REPLICADORES DE NETWORK MARKETING</b>. Indica a un conocido para que también suba los inmuebles de IAMOVING en sus redes y siempre que este conocido reciba una comisión, el colaborador que ha recomendado recibirá una comisión extra por haber traído a este nuevo colaborador a la plataforma.</p>
			<p>2.1 - El Colaborador podrá desempeñar su actividad sin necesidad de establecerse en oficina alguna, en una oficina de otro Colaborador respetando normas de uso del propietario de dicha oficina o en su propio domicilio.</p>
<!--			<p>2.3 - El Colaborador está obligado a usar la imagen de IAMOVING ONLINE, S.L. en cualquiera de sus manifestaciones únicamente mediante autorización previa de la dirección de IAMOVING ONLINE, S.L. y siempre limitándolo al cumplimiento estricto de los servicios objeto del presente Contrato de colaboración.</p>-->
			<p>2.2 - El Colaborador podrá prestar sus servicios para otras empresas, por cuenta propia o ajena, remunerada o no remunerada, siempre y cuando esas compañías no pertenezcan a la competencia de IAMOVING ONLINE, S.L., <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a>. En cualquier caso, si el Colaborador deseara prestar servicios para otra empresa, sea competencia o no de IAMOVING ONLINE, S.L., deberá comunicarlo previamente a ésta para que la mercantil pueda decidir sobre la posible resolución del presente acuerdo de colaboración. En este sentido, el Colaborador manifiesta no estar desempeñando las funciones que realizará con IAMOVING ONLINE, S.L. y <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a>, para ninguna otra empresa. </p>
			<p>2.3 - El colaborador no está autorizado a concluir negocios, ni pasar el teléfono de los inmuebles que el mismo ha encontrado ejerciendo su función de comercial, en nombre de IAMOVING ONLINE, S.L., en nombre de las empresas con las cuales la mercantil tenga un contrato de cooperación firmado (en adelante “Empresas Asociadas”), en su nombre, o en nombre de algún pariente o de terceros. El colaborador tampoco está facultado para realizar o recibir declaraciones escritas o verbales que pudieran ser vinculantes para IAMOVING ONLINE, S.L. En particular, no podrá decidir sobre la aceptación o denegación de contratos o solicitudes, ni acordar modificaciones o renovaciones de contrato, ni conceder permisos de cobertura ni aplazar el pago de fianzas o mensualidades, u otras cantidades percibidas del cliente por cualquier concepto. </p>
			<p>2.4 - El Colaborador no está autorizado para recibir pagos, cualquiera que sea su naturaleza, por cuenta de IAMOVING ONLINE, S.L, o de sus Empresas Asociadas, ni para prometer u otorgar a los clientes de IAMOVING ONLINE, S.L, retribución alguna ni pagarles comisiones. Asimismo, el Colaborador no está facultado para percibir del cliente una retribución por sus servicios.</p>
			<p>2.5 - El colaborador que realiza visitas para <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a>, no puede permitir que los propietarios, agencias inmobiliarias, compradores e inquilinos intercambien sus teléfonos y/o correos electrónicos entre ellos o entre terceros relacionados con la visita en la que IAMOVING ha sido responsable</p>
			<p>2.6 - El colaborador de IAMOVING, bajo en ningún concepto, podrá hacer el papel de intermediario por cuenta propia o través de terceros tales como: algún pariente, conocidos o a través de otras empresas, vendiendo o alquilando un inmueble gestionado por IAMOVING para sí mismo, para algún pariente, para alguna de las personas que IAMOVING les hubiera enviado para la realización de las visitas o para terceros, en la que IAMOVING no haya tenido conocimiento o consentimiento de dicha operación.</p>
			<p>4 - <b>PENALIZACIÓN COLABORADOR IAMOVING</b>.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; -Que en el caso de que el COLOBORADOR de IAMOVING contravenga las cláusulas anteriores mencionadas en los apartados <b>2.3, 2.4, 2.5, 2.6</b>, el COLABORADOR tendrá la obligación de abonar unos importes correspondientes a un 6% + IVA referente al precio del inmueble en el que haya ocurrido la incidencia, en el caso de que se trate de una venta y de un mes+ iva en las operaciones de alquiler, ambos en concepto de penalización.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; -En el caso que el <b>COLABORADOR DE VISITAS IAMOVING, COLABORADOR AUDIOVISUAL IAMOVING o COLABORADOR FOTOGRAFICO IAMOVING</b> no asista a una visita ya confirmada y no lo notifique a las partes involucradas, con un mínimo de 2 horas de antelación respecto a la hora confirmada entre las partes, este colaborador deberá abonar a la plataforma una penalización de 50€. En el caso de que esta situación se repita, la relación entre el colaborador y la plataforma quedará finalizada inmediatamente.</p>
			
			<h5>5 - OBLIGACIONES Y DERECHOS DE IAMOVING ONLINE, S.L.</h5>
			<p>5.1 - IAMOVING ONLINE, S.L. pondrá a disposición del Colaborador los documentos necesarios para la realización de su actividad, estos documentos seguirán siendo propiedad de IAMOVING ONLINE, S.L.</p>
			<p>5.2 - IAMOVING ONLINE, S.L. apoyará con su máximo esfuerzo al Colaborador en la realización de su actividad.</p>
			<p>5.3 - IAMOVING ONLINE, S.L. únicamente utilizará los datos del Colaborador almacenados en bases de datos conforme a este acuerdo de colaboración y de conformidad con las disposiciones legales aplicables en materia de nuestra de protección de datos.</p>
			<h5>6 - CONFIDENCIALIDAD</h5>
			<p>6.1 - El Colaborador deberá guardar silencio sobre cualquier información relativa a IAMOVING ONLINE, S.L. de la que adquiera conocimiento durante el ejercicio de su actividad. Asimismo, no aprovechará, ni en beneficio propio ni en el de terceros, información alguna a la que haya accedido durante o en virtud de la prestación de servicios objeto del presente Contrato de colaboración. Forman parte de dicha información los datos relativos a los contratos, los datos personales y domicilios de los clientes. También forman parte de dicha información los datos de los que el Colaborador adquiera conocimiento a través de la utilización de medios de IAMOVING ONLINE, S.L.. Las anteriores obligaciones permanecerán vigentes con posterioridad a la terminación de este Contrato de colaboración. El Colaborador se responsabiliza a que los eventuales trabajadores propios del Colaborador que haya contratado para la prestación de los servicios objeto de este Contrato de colaboración también cumplan la obligación de confidencialidad.</p>
			<h5>7 - REMUNERACIÓN</h5>
			<p>7.1 - <b>(SOLO COLABORADOR AUDIOVISUAL IAMOVING) VISITA VIRTUAL- (30 €)</b>. A partir de la segunda visita el agente colaborador percibirá honorarios. De la primera visita, el agente colaborador no percibirá ningún honorario, pues el primer trabajo de colaborador será de prueba.</p>
			<p>7.2 - <b>(SOLO COLABORADOR FOTOGRAFICO IAMOVING) VISITA VIRTUAL- (15 €)</b>. A partir de la segunda visita el agente colaborador percibirá honorarios. De la primera visita, el agente colaborador no percibirá ningún honorario, pues el primer trabajo de colaborador será de prueba.</p>	
			<p>7.3 - <b>COLABORADOR COMERCIAL</b>. Se abonará <b>10 €</b> por cada inmueble que dicho comercial haya recabado y que la misma haya publicado en la plataforma IAMOVING + su comisión correspondiente mencionada abajo en el punto <b>7.4 B</b>, siempre cuando IAMOVING sea el anunciante del inmueble publicado en la plataforma.</p>	
			<p>7.4 - <b>COLABORADOR INFLUENCER INMOBILIARIO Y COMERCIAL</b>:</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; <b>A.-COLABORADOR INFLUENCER INMOBILIARIO PARA CAPTAR COMPRADORES O INQUILINOS</b>. Se establece en el 10% de comisión de alquiler o venta al Colaborador, sobre los honorarios netos que recibe la plataforma, siempre y cuando el Colaborador haya realizado la captación de un inquilino o comprador que provocó el alquiler o la venta respectivamente.</p>
			<p>&nbsp; &nbsp; &nbsp; &nbsp; <b>B.-COLABORADOR COMERCIAL CASO DE CAPTACIÓN DE INMUEBLES A LA PLATAFORMA</b>. Se establece en el 10% de comisión de alquiler o venta al Colaborador, sobre los honorarios netos que recibe la plataforma, siempre cuando el Colaborador haya realizado la captación que provocó la venta.</p>			
			<p>7.5 - <b>COLABORADOR DE VISITAS</b>. Su función consiste en enseñar inmuebles a posibles compradores o arrendatarios para la plataforma. El colaborador recibirá 15€ por cada hora en la que realice esta función. Se establece en el 10% de comisión de alquiler o venta al Colaborador, sobre los honorarios netos que recibe la plataforma, siempre cuando el Colaborador haya realizado la visita física que provocó el alquiler o la venta respectivamente.</p>
			<p>7.6 - <b>COLABORADOR DE VISITAS + FOTOS + INFORMACIÓN</b>. En el caso que el colaborador realice la visita presencial, haga fotos, video rápido y actualice los anuncios de <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a> e <a href="https://www.idealista.com" style="color:#EADD03;">www.idealista.com</a>, con las fotos, video rápido y la información del inmueble, este recibirá un extra de 10€, siempre cuando sea una petición de la plataforma.</p>
			<p>7.7 - <b>COLABORADOR DE VISITAS + FOTOS, VIDEO + INFORMACIÓN </b>. En el caso que el colaborador realice la visita presencial, video y lo edite, haga fotos y actualice los anuncios de <a href="https://www.iamoving.com" style="color:#EADD03;">www.iamoving.com</a> e <a href="https://www.idealista.com" style="color:#EADD03;">www.idealista.com</a>, con las fotos y la información del inmueble, este recibirá un extra de 15€, siempre cuando sea una petición de la plataforma.</p>
			<p>7.8 - <b>– REPLICADOR EN NETWORK MARKETING</b>. Se establece en el 5% de comisión de alquiler o venta al Colaborador, sobre los honorarios netos que recibe la plataforma, siempre en el caso de que el comprador o inquilino haya venido por un colaborador influencer inmobiliario, que el Colaborador haya indicado a la plataforma.</p>
			<p>7.9 - <b>COLABORADOR COMERCIAL PARA LA PLATAFORMA <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a></b> Se abonará (25,00€) por las 5 habitaciones que sean publicadas en la plataforma <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a>que tengan el número de referencia del colaborador, en concepto de prestación de sus servicios a la plataforma mencionados en el punto 2.f</p>
			<p>7.10 - <b>COLABORADOR AUDIOVISUAL <a href="https://WWW.BED4EXCHANGE.COM" style="color:#EADD03;">WWW.BED4EXCHANGE.COM</a></b> Se abonarán (10,00€) por cada video, en concepto de prestación de sus servicios a la plataforma mencionados en el punto 2.6.</p>
			<h5>8 - PAGOS Y COSTES</h5>
			<p>8.1 - Las anteriores cantidades serán abonadas por IAMOVING ONLINE, S.L. todos los lunes, siempre cuando el colaborador entregue a la plataforma el trabajo realizado, en el número de cuenta que el Colaborador facilite a la mercantil. <b>COMSIONES</b>. En las cláusulas <b>7.4 A, 7.4 B y 7.5</b>, IAMOVING abonará a los colaboradores, una vez que se firme cada operación y la misma haya recibido los honorarios correspondientes del contratante. En dicha cantidad no se incluyen las cantidades que puedan derivarse de los impuestos y tasas correspondientes a las facturas que presente el colaborador.</p>			
			<p>8.2 - Cualquier tipo de gasto extraordinario que se produzca como consecuencia del desempeño de las funciones y obligaciones del Colaborador para con IAMOVING ONLINE, S.L. serán abonadas, asumidas por el colaborador, sin que le pueda repercutir ningún gasto a la empresa.</p>			
			<p>8.3 - En caso de que el colaborador incurra en cualquier tipo de falta o indisciplina (faltas de respeto a clientes, impuntualidad, falta de disposición, etc.) para con los clientes o para con IAMOVING ONLINE, S.L., ésta estará facultada para revisar de manera unilateral la remuneración y, de ser necesario, que el colaborador perciba una cantidad inferior a la estipulada.</p>			
			<h5>9 - CESIÓN DE DERECHOS DE EXPLOTACIÓN</h5>
			<p>9.1- Que en el desarrollo de las funciones propias del término que suscribe; el Colaborador realizará, entre otros, fotos y videos de inmuebles y otros, así como fotos y videos explicativos y/o comerciales en los que podría aparecer su propia imagen. su voz o ambas y que se proporcionarán a la empresa dentro del acuerdo existente. En atención a lo anterior y en cumplimiento de lo establecido en la Ley Orgánica 1/1982, de 5 de mayor de protección civil del derecho al honor, a la intimidad personal y familiar y a la propia imagen, como en el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016 relativo a la protección de las personas físicas en lo que respecta al tratamiento de datos personales y libre circulación de estos datos, así como, en el Real Decreto Legislativo 1/1996, de 12 de abril, por el que se aprueba el texto refundido en la Ley de Propiedad Intelectual, regularizando, aclarando y armonizando las disposiciones legales vigentes sobre la materia; el trabajador CONSIENTE y AUTORIZA EXPRESAMENTE a la empresa para que utilice, reproduzca, distribuya y publique tanto las creaciones de foto y video de las propiedades o cualquier otra que el Colaborador realice en el desarrollo de sus servicios prestados, así como a que utilice y publique todas aquellas en las que aparezca su imagen física y/o su voz con o sin movimiento, incluido su subtítulo o doblaje en caso de que fuera necesario, con fines comerciales o no y para que, en concreto, puedan ser publicadas en:</p>			
			<p>&nbsp; &nbsp; &nbsp; &nbsp; A. Página web de la empresa y perfiles en redes sociales (Twitter, Facebook, Instagram, LinkedIn, TikTok, YouTube y cualquier otra que considerara oportuna la empresa). Filmaciones destinadas a difusión comercial, fotografías para revistas o publicaciones de ámbito relacionado con el sector de la empresa.</p>			
			<p>&nbsp; &nbsp; &nbsp; &nbsp; B. Que la anterior cesión de derechos de explotación así como la cesión de derechos de imagen se acuerdan con una duración indefinida y que se extenderá incluso una vez haya finalizado la relación que vincula a las partes a través de este término y condiciones y de tal forma que, en este último caso, la empresa podrá seguir utilizando, reproduciendo, distribuyendo y publicando tanto las creaciones de foto y video realizadas por el Colaborador como todas aquellas fotos y videos en las que aparezca su imagen física y/o su voz y sin que nada pueda reclamarse por ello por parte del Colaborador y sin que en ningún caso pueda solicitar la eliminación de dicho contenido. Que ambas partes acuerdas que no corresponde retribución adicional alguna por la cesión de derechos acordada en la presente cláusula.</p>			
			<p>9.2 - El presente término también tiene por objeto la cesión por parte del Colaborador a favor de IAMOVING del derecho de reproducción, distribución y comunicación pública de las aportaciones creativas realizadas por el Colaborador durante la producción cualquiera de sus visitas para su transformación en formato audiovisual con el único fin de permitir la explotación comercial de dichas visitas resultante en la forma y el alcance que libremente determine IAMOVING. Esta cesión es de carácter permanente e indefinida, sin que por parte del Colaborador pueda reclamarse nada a futuro con respecto al contenido de las visitas. El Colaborador reconoce que, respecto a todos aquellos materiales adicionales propiedad de terceros que haya utilizado para realizar las visitas, tales como imágenes gráficas, logos, dibujos, marcas, material audiovisual, nombres, fotografías, etc., ha obtenido la correspondiente autorización de su titular para su publicación e inclusión en la visita entregada a IAMOVING en la forma acordada sin que ello constituya una vulneración.</p>			
			<p>9.3 - Igualmente, será objeto de cesión a favor de IAMOVING, los derechos de imagen del Colaborador comprendiendo sus explicaciones, su voz, su imagen física con o sin movimiento fijadas en la visita, incluido su subtitulado o doblaje en caso de que fuera necesario. Todo ello con la única salvedad y limitación de aquellos usos o aplicaciones que pudieran atentar contra el derecho al honor del Colaborador en los términos previstos en la legislación vigente. A tal efecto, la totalidad de los contenidos con aportaciones creativas del Colaborador a cada visita, así como la imagen del Colaborador, y materiales que formen parte de la visita se identifican, conjuntamente a efectos del presente Contrato, como los “Contenidos”.</p>									
			<h5>10 - INICIO, DURACIÓN, RESCISIÓN Y FINALIZACIÓN DEL ACUERDO DE COLABORACIÓN</h5>
			<p>10.1 - El presente término de colaboración tendrá una duración indefinida, el acuerdo de colaboración podrá resolverse por cualquiera de las dos partes con un plazo de preaviso mínimo de un mes. En cualquier caso, la rescisión del acuerdo de colaboración podrá producirse con efectos inmediatos en caso de que ambas partes renuncien y que sea de mutuo acuerdo.</p>			
			<p>10.2 - Sin perjuicio de lo anterior, IAMOVING ONLINE, S.L. podrá resolver el acuerdo de colaboración de manera unilateral siempre y cuando considere que el Colaborador está incumpliendo alguna de sus obligaciones y derechos.</p>			
			<h5>11 - DISPOSICIONES FINALES</h5>
			<p>11.1 - Si alguna disposición existente o que se recoja en el futuro al acuerdo de colaboración resultara sin fuerza legal, fuera por la causa que fuese, las partes acuerdan que ello no afectará a la eficacia legal de las restantes disposiciones del término de colaboración. Esto será aplicable asimismo para el caso de modificación o cambio de la ley vigente, para variaciones de la jurisprudencia aplicable o para el supuesto de que exista una laguna claramente perceptible en el término de colaboración.</p>			
			<p>En ese caso, las partes convienen que se considerará como válida una regulación - en la medida en que sea legalmente posible - que cumpla de la mejor manera posible lo que las partes pretendían con la disposición invalidada de acuerdo con el sentido y los fines del término de colaboración, siempre que las partes hubieran previsto dicha circunstancia a la aceptación del término de colaboración o al incluir la disposición en el mismo. Esto tendrá también vigencia en el supuesto de que la invalidación de una disposición se base en una norma legal. Entonces se considerará acordada una prestación o un tiempo, un plazo o una fecha que sea lo más parecida posible en sus efectos a lo que se pretendía con la medida invalidada.</p>			
			<p>11.2 - El presente termino de colaboración no constituye una relación laboral ni cualquier otra de dependencia entre IAMOVING ONLINE, S.L. y el Colaborador. Asimismo, las partes manifiestan que su voluntad no es la de constituir una relación contractual de las reguladas por la actual legislación.</p>			
			<p>11.3- Para cualquier discrepancia que pudiera surgir de los términos de colaboración que las partes acuerdan, con renuncia expresa a cualquier otro fuero que les pudiera corresponder, someterse a los Juzgados y Tribunales de la ciudad de Madrid capital.</p>
        </div>
    </body>
</html>